### ISSUE TITLE
 com.aliyun.openservices.ons.api.exception.ONSClientException: The consumer group[CID_recent_update_111] has been created before

### ISSUE THREAD

**Issue by xghrbc1001** [alibaba-archive/ons#11]
web工程启动时报如下错误

```
Exception in thread "Thread-5" com.aliyun.openservices.ons.api.exception.ONSClientException: The consumer group[CID_recent_update_111] has been created before, specify another name please.
See https://github.com/alibaba/RocketMQ/issues/40 for further details.
    at com.aliyun.openservices.ons.api.impl.rocketmq.ConsumerImpl.start(ConsumerImpl.java:71)
    at com.jindidata.service.mq.impl.MQServiceImpl$2.run(MQServiceImpl.java:105)
Caused by: com.alibaba.rocketmq.client.exception.MQClientException: The consumer group[CID_recent_update_111] has been created before, specify another name please.
See https://github.com/alibaba/RocketMQ/issues/40 for further details.
    at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:759)
    at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:363)
    at com.aliyun.openservices.ons.api.impl.rocketmq.ConsumerImpl.start(ConsumerImpl.java:68)
    ... 1 more
```

场景是这样的，web工程部署在多台机器上，consumer都是CID_recent_update_111,producer都是Topic_recent_update

**Comment by xghrbc1001** [comment]
顺便问下，有没有交流的qq群，谢谢

**Comment by esperyong** [comment]
真他妈垃圾的产品
