### ISSUE TITLE
Broker返回异常

### ISSUE THREAD

**Issue by vintagewang** [alibaba-archive/ons#5]

**Comment by wangjiangshan** [comment]
Exception in thread "main" com.aliyun.openservices.ons.api.exception.ONSClientException: Receive a broker exception, Topic: wangjs-ons, com.aliyun.openservices.ons.api.impl.authority.exception.AuthenticationException: valid permission failed., com.alibaba.ons.open.auth.validator.PermissionValidator.aliyun(PermissionValidator.java:66)
但ACCESSKEY和SERETKEY都是对的

**Comment by smellmine** [comment]
仔细看下，有可能是该topic：wangjs-ons不属于producerID

**Comment by xc145214** [comment]
ons的demo项目里报这个错，是不是因为AccessKey和SecretKey的设置不正确？

```
com.aliyun.openservices.ons.api.exception.ONSClientException: Receive a broker exception, Topic: EC_TEST, com.aliyun.openservices.ons.api.impl.authority.exception.AuthenticationException: check from ubsms failed. enable=false, com.alibaba.ons.open.auth.ubsms.UbsmsServiceManager.isResourceEnabled(UbsmsServiceManager.java:91)
See https://github.com/alibaba/ons/issues/5 for further details.
    at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.checkProducerException(ProducerImpl.java:106)
    at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.send(ProducerImpl.java:147)
    at ons.example.producer.OnsProducer.send(OnsProducer.java:53)
    at ons.example.producer.OnsProducer.main(OnsProducer.java:84)
```

**Comment by renfufei** [comment]
有一种情况。是使用了阿里云的 RAM 子账号权限体系。那么，需要在Topic管理的地方，授权给子账号或者其他账号。
